apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  namespace: prod
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      initContainers:
        - name: init-mydb
          image: busybox
          command:
            - sh
            - -c
            - until nslookup vprodb.prod.svc.cluster.local; do echo waiting for mydb; sleep 2; done;
        - name: init-memcache
          image: busybox
          command:
            - sh
            - -c
            - until nslookup vprocache01.prod.svc.cluster.local; do echo waiting for memcache; sleep 2; done;
      containers:
        - name: vproapp
          image: huzaifh02/vprofileapp:12
          ports:
            - containerPort: 8080
